package com.mmxb.mgr.mapper;

import com.mmxb.mgr.pojo.ManagerRoles;
import com.mmxb.mgr.pojo.ManagerRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int countByExample(ManagerRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int deleteByExample(ManagerRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int insert(ManagerRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int insertSelective(ManagerRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    List<ManagerRoles> selectByExample(ManagerRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    ManagerRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ManagerRoles record, @Param("example") ManagerRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ManagerRoles record, @Param("example") ManagerRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManagerRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManagerRoles record);
}