package com.mmxb.mgr.pojo;

public class Car {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.is_rentaling
     *
     * @mbggenerated
     */
    private String isRentaling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.shop_id
     *
     * @mbggenerated
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_status
     *
     * @mbggenerated
     */
    private String carStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_number
     *
     * @mbggenerated
     */
    private String carNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_type
     *
     * @mbggenerated
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.shop_name
     *
     * @mbggenerated
     */
    private String shopName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.id
     *
     * @return the value of car.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.id
     *
     * @param id the value for car.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.is_rentaling
     *
     * @return the value of car.is_rentaling
     *
     * @mbggenerated
     */
    public String getIsRentaling() {
        return isRentaling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.is_rentaling
     *
     * @param isRentaling the value for car.is_rentaling
     *
     * @mbggenerated
     */
    public void setIsRentaling(String isRentaling) {
        this.isRentaling = isRentaling == null ? null : isRentaling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.shop_id
     *
     * @return the value of car.shop_id
     *
     * @mbggenerated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.shop_id
     *
     * @param shopId the value for car.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_status
     *
     * @return the value of car.car_status
     *
     * @mbggenerated
     */
    public String getCarStatus() {
        return carStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_status
     *
     * @param carStatus the value for car.car_status
     *
     * @mbggenerated
     */
    public void setCarStatus(String carStatus) {
        this.carStatus = carStatus == null ? null : carStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_number
     *
     * @return the value of car.car_number
     *
     * @mbggenerated
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_number
     *
     * @param carNumber the value for car.car_number
     *
     * @mbggenerated
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber == null ? null : carNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_type
     *
     * @return the value of car.car_type
     *
     * @mbggenerated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_type
     *
     * @param carType the value for car.car_type
     *
     * @mbggenerated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.shop_name
     *
     * @return the value of car.shop_name
     *
     * @mbggenerated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.shop_name
     *
     * @param shopName the value for car.shop_name
     *
     * @mbggenerated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }
}